services:
  db:
    platform: linux/amd64
    image: postgres:16-bookworm
    container_name: db
    volumes:
      - type: volume
        source: pg_data
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - env/local.env
    restart: always

  app:
    platform: linux/amd64
    container_name: app
    build: 
      context: ./keybort
    volumes:
      - type: bind
        source: ./keybort
        target: /keybort
    working_dir: /keybort
    ports:
      - 8000:8000
    env_file:
      - env/local.env
    depends_on:
      - db
    restart: always
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  pg_data: