# Generated by Django 5.0.7 on 2024-08-05 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keycaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=32, null=True)),
                ('total_keys', models.PositiveIntegerField(blank=True, null=True)),
                ('pcb', models.CharField(blank=True, max_length=255, null=True)),
                ('layout', models.CharField(blank=True, help_text='Refers to physical layout, not the individual caps placed on each switch (i.e. Dvorak, QZERTY).', max_length=255, null=True)),
                ('case_material', models.CharField(blank=True, max_length=255, null=True)),
                ('mount_type', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('flex_cuts', models.BooleanField(default=False)),
                ('half', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stabilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, choices=[('l', 'Linear'), ('sl', 'Silent Linear'), ('t', 'Tactile'), ('st', 'Silent Tactile'), ('c', 'Clicky')], max_length=255, null=True)),
                ('stem', models.CharField(blank=True, choices=[('mx', 'MX'), ('topre', 'Topre'), ('alps', 'Alps')], default='mx', max_length=255, null=True)),
                ('peak_force', models.FloatField(blank=True, help_text='gf', null=True)),
                ('bottom_out_force', models.FloatField(blank=True, help_text='gf', null=True)),
                ('travel_distance', models.FloatField(blank=True, help_text='mm', null=True)),
                ('top_housing', models.CharField(blank=True, choices=[('abs', 'ABS'), ('nylon', 'Nylon'), ('pc', 'Polycarbonate'), ('pe', 'Polyethylene'), ('pom', 'POM')], max_length=255, null=True)),
                ('bottom_housing', models.CharField(blank=True, choices=[('abs', 'ABS'), ('nylon', 'Nylon'), ('pc', 'Polycarbonate'), ('pe', 'Polyethylene'), ('pom', 'POM')], max_length=255, null=True)),
                ('lubed', models.BooleanField(default=False)),
                ('filmed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('mod', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prebuilt', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
                ('wireless', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('references', models.TextField(blank=True, help_text='Documentation, QMK info, etc.', null=True)),
                ('keycaps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.keycaps')),
                ('kit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.kit')),
                ('plate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.plate')),
                ('stabilizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.stabilizer')),
                ('switch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.switch')),
            ],
        ),
    ]
